on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: "Login to Docker hub"
        run: docker login --username shimaa1234 --password dckr_pat_C8uMQIrZbRnkYs-09jLJj2CzLaM
      

      